import smtplib
import ssl
from email.message import EmailMessage

import streamlit as st
from google import genai
from google.genai import types

from prompts import SYSTEM_PROMPT


# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------

st.set_page_config(
    page_title="SnapStudy",
    page_icon="📚"
)

st.title("📚 SnapStudy")
st.caption("Upload your study material and ask questions about it.")


# --------------------------------------------------
# GEMINI
# --------------------------------------------------

GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]


@st.cache_resource
def get_gemini_client():
    return genai.Client(api_key=GEMINI_API_KEY)


gemini_client = get_gemini_client()


# --------------------------------------------------
# CHAT SESSION
# --------------------------------------------------

if "chat" not in st.session_state:
    st.session_state.chat = gemini_client.chats.create(
        model="gemini-3.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT
        )
    )


if "last_question" not in st.session_state:
    st.session_state.last_question = None


if "last_answer" not in st.session_state:
    st.session_state.last_answer = None


# --------------------------------------------------
# EMAIL FUNCTION
# --------------------------------------------------

def send_email(recipient_email, question, answer):

    smtp_user = st.secrets["SMTP_USER"]
    smtp_password = st.secrets["SMTP_APP_PASSWORD"]

    message = EmailMessage()

    message["Subject"] = "📚 SnapStudy - Your Study Answer"
    message["From"] = smtp_user
    message["To"] = recipient_email

    email_body = f"""
Hello,

Here is your SnapStudy answer.

Question:
{question}

Answer:
{answer}

--------------------------------
Generated by SnapStudy 📚
"""

    message.set_content(email_body)

    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(
        "smtp.gmail.com",
        465,
        context=context
    ) as server:

        server.login(
            smtp_user,
            smtp_password
        )

        server.send_message(message)


# --------------------------------------------------
# FILE UPLOAD
# --------------------------------------------------

uploaded_file = st.file_uploader(
    "📷 Upload your syllabus, timetable, assignment, or notes",
    type=["jpg", "jpeg", "png"]
)


# --------------------------------------------------
# ASK QUESTION
# --------------------------------------------------

if uploaded_file:

    st.image(
        uploaded_file,
        caption="Uploaded material",
        use_container_width=True
    )

    question = st.chat_input(
        "Ask something about this material..."
    )

    if question:

        image_bytes = uploaded_file.getvalue()

        parts = [
            types.Part.from_bytes(
                data=image_bytes,
                mime_type=uploaded_file.type
            ),
            question
        ]

        with st.spinner("Analyzing your material..."):

            try:

                response = st.session_state.chat.send_message(
                    parts
                )

                answer = response.text

                # Save latest question and answer
                st.session_state.last_question = question
                st.session_state.last_answer = answer

                st.chat_message("user").write(question)

                st.chat_message("assistant").write(answer)

            except Exception as error:

                st.error(
                    f"Something went wrong: {error}"
                )


# --------------------------------------------------
# EMAIL SHARING
# --------------------------------------------------

if st.session_state.last_answer:

    st.divider()

    st.subheader("📧 Email this answer")

    recipient_email = st.text_input(
        "Enter your email address",
        placeholder="student@example.com"
    )

    if st.button("📨 Send Answer"):

        if not recipient_email:
            st.warning(
                "Please enter an email address."
            )

        elif "@" not in recipient_email:
            st.warning(
                "Please enter a valid email address."
            )

        else:

            with st.spinner("Sending email..."):

                try:

                    send_email(
                        recipient_email,
                        st.session_state.last_question,
                        st.session_state.last_answer
                    )

                    st.success(
                        "✅ Answer sent successfully!"
                    )

                except Exception as error:

                    st.error(
                        f"Failed to send email: {error}"
                    )